### ISSUE TITLE
Thumb image and main image in recipes

### ISSUE THREAD

**Issue by marcin-kopanski** [marcin-kopanski/diet-coach-website#3]
Przy dodawaniu przepisu potrzebna będzie również możliwość dodania miniaturki przepisu, aby obraz wyświetlany na stronie głównej był odpowiedniej rozdzielczości

**Comment by mikklein** [comment]
Na telefonach w cenniku oferty nie powinny być rozciągnięte na całą szerokość

**Comment by mikklein** [comment]
Formularz powinien być wysyłany na adres gab.rownowaga@gmail.com , nie marcin.kopanski@gmail.com

**Comment by marcin-kopanski** [comment]
zrobione
