### ISSUE TITLE
Wyświetlanie google map

### ISSUE THREAD

**Issue by mikklein** [marcin-kopanski/diet-coach-website#4]
Mapa znika gdy zwiniemy stronę do małych rozdzielczości

**Comment by marcin-kopanski** [comment]
@mikklein z ta mapka to jest roboty, pobawie sie z tym jeszcze jutro

**Comment by mikklein** [comment]
@marcin-kopanski zastanawiam się czy nie wyświetlić w miejsce mapy statycznego zdjęcia, a jak użytkownik kliknie na mape, to albo wtedy przekierujemy go do google maps, albo wtedy pobierzemy mapkę, z tego co widzę w internecie to dość popularne, pozwala zaoszczędzić sporo requestów przy wczytywaniu strony. Zostawmy to na później, wieczorem przyjrzę się temu dokładniej

**Comment by marcin-kopanski** [comment]
oczywiście, że lepiej zastapić to obrazkiem i wokół dodać link do mapsów, jak dostarczysz obrazek to podmienię

**Comment by marcin-kopanski** [comment]
hej, mozesz podbic jeszcze raz obrazki do gita i na strone? znowu sie
podmienily przez merge. masz teraz uprawnienia i mozesz pushowac prosto do
mastera


Pozdrawiam

Marcin Kopański

W dniu 3 grudnia 2017 10:30 użytkownik mikklein <notifications@github.com>
napisał:
