### ISSUE TITLE
Stylizacja strony głównej

### ISSUE THREAD

**Issue by mikklein** [marcin-kopanski/diet-coach-website#5]
Do tego będą potrzebne nowe źródła z c9. Jest tam dopracowany kalkulator oraz przykładowe przepisy.

Przydałoby się stylizacja przepisów aby nie były takie gołe na stronce. Może jakiś header, np "przykładowe przepisy" u góry i zapakowanie je w jubotrona?

Stylowanie kalkulatora BMI, aby wyglądał spójnie ze stroną. Można wydzielić jego js do odpowiedniego pliku. Bo teraz został wrzucony do kodu html

**Comment by marcin-kopanski** [comment]
@mikklein zmienilem style kalkulatora, organizacje js to juz mozesz sobie zrobic
