### ISSUE TITLE
Dodanie tagów w sekcji "head"

### ISSUE THREAD

**Issue by mikklein** [marcin-kopanski/diet-coach-website#7]
<meta name="keywords"  content="dietetyk, dietetyk gdańsk, trójmiasto, dieta, odchudzanie, równowaga" />
<meta name="description" content="Poradnia dietetyczna w Gdańsku, układanie diet, doradztwo żywieniowe, oraz potrzbną motywacje w trakcie  " >

<title>Dietetyk Psycholog Gdańsk</title>

**Comment by mikklein** [comment]
<meta name="keywords"  content="dietetyk, dietetyk gdańsk, trójmiasto, dieta, odchudzanie, równowaga" />
<meta name="description" content="Poradnia dietetyczna w Gdańsku,  oferuje ułożenie diety, jadłospisy, motywacje, oraz terapie">

**Comment by marcin-kopanski** [comment]
@mikklein 
zrobione, jesli chcesz to zmieniac to DefaultPageContentConcern -> set_page_defaults
